import Head from "next/head";
import { useEffect, useState, useRef } from "react";

const filters = [
  // { vendorId: 0x2fe3, productId: 0x0100 },
  // { vendorId: 0x2fe3, productId: 0x00a },
  // { vendorId: 0x8086, productId: 0xf8a1 },
];

export default function Home() {
  //States
  const [senderArea, setSenderArea] = useState("Type a message here:");
  const [reciverArea, setReciverArea] = useState("");
  const [endpointIn, setEndpointIn] = useState();
  const [endpointOut, setEndpointOut] = useState();

  //pointer equivalent
  let portRef = useRef();

  //Functions

  //This function allows for establising connection with a usb device.
  const Connect = async () => {
    try {
      // setDevice(request);
      let request = await navigator.usb.requestDevice({ filters: filters });
      portRef.current = request;

      //endpoints setup
      let endpointIn =
        request.configuration.interfaces[2].alternate.endpoints.filter(
          (endpoint) => endpoint.direction !== "out"
        )[0];
      setEndpointIn(endpointIn);
      let endpointOut =
        request.configuration.interfaces[2].alternate.endpoints.filter(
          (endpoint) => endpoint.direction !== "in"
        )[0];
      setEndpointOut(endpointOut);

      await request.open();
      if (request.configuration === null) await request.selectConfiguration(1);
      await request.claimInterface(
        request.configuration.interfaces[2].interfaceNumber
      );
      Listen();
      console.log(response);
    } catch (error) {
      portRef.current.close();
      console.log(error, "error");
    }
  };

  //A function for listening for incoming WebUSB tranfers.
  //This is a recursive function as it has to always listen for
  //incoming transfers. It is in effect a Receive function.
  let Listen = () => {
    if (!portRef.current) return;

    requestRef.current
      .transferIn(endpointIn.endpointNumber, 64)
      .then((data) => {
        setReciverArea(new TextDecoder().decode(data));
        Listen();
      });
  };

  //A function for reading a binary file. Takes the input of the
  //"choose file" button.
  const ReadFile = async (input) => {
    let file = input.target.files[0];
    let reader = new FileReader();
    reader.readAsArrayBuffer(file);
    reader.onload = function () {
      console.log(reader.result);
      Send(reader);
    };
    reader.onerror = function () {
      console.log(reader.error);
    };
    console.log(input);
  };

  //This function allows for sending data to the connected
  //usb device. Data has to be of string type.
  const Send = (data) => {
    if (!portRef.current) return;
    console.log(portRef);
    console.log("sending to serial:" + data.length);
    if (data.length === 0) return;
    console.log("sending to serial: [" + data + "]\n");

    //converting the data into to utf-8 format
    let view = new TextEncoder().encode(data);
    console.log(view);
    requestRef.current.transferOut(endpointOut.endpointNumber, view);
  };

  //Rendered wabpage contents/ DOM structure
  return (
    <>
      <Head>
        <title>Delta WebUSB App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Delta WebUSB App demo</h1>
      <h2></h2>
      <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
        <button
          id="connect"
          onClick={Connect}
          style={{ visibility: "visible", maxWidth: "max-content" }}
        >
          Connect To WebUSB Device
        </button>
        <div
          style={{
            marginTop: 100,
          }}
        >
          <input type="file" onChange={ReadFile}></input>
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            marginTop: 150,
          }}
        >
          <button id="submit" onClick={() => Send(senderArea)}>
            Send
          </button>
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            gap: 15,
          }}
        >
          <label htmlFor="editor">Sender: </label>
          <textarea
            id="editor"
            cols={30}
            onChange={(e) => setSenderArea(e.target.value)}
            value={senderArea}
          ></textarea>
          <label htmlFor="output"> Receiver: </label>
          <textarea
            id="output"
            cols={30}
            readOnly
            value={reciverArea}
          ></textarea>
        </div>
      </div>
    </>
  );
}
