import Head from "next/head";
import { useEffect, useState, useRef } from "react";

const filters = [
  // { vendorId: 0x2fe3, productId: 0x0100 },
  // { vendorId: 0x2fe3, productId: 0x00a },
  // { vendorId: 0x8086, productId: 0xf8a1 },
];

export default function Home() {
  //States
  const [device, setDevice] = useState();
  const [senderArea, setSenderArea] = useState("Type a message here:");
  const [reciverArea, setReciverArea] = useState("");

  //pointer equivalent
  let portRef = useRef();

  //Functions
  const connect = async () => {
    try {
      // setDevice(request);
      let request = await navigator.usb.requestDevice({ filters: filters });
      portRef.current = request;

      let endpoint =
        request.configuration.interfaces[2].alternate.endpoints.filter(
          (endpoint) => endpoint.direction !== "out"
        )[0];
      console.log(endpoint);

      await request.open();
      if (request.configuration === null) await request.selectConfiguration(1);

      await request.claimInterface(
        request.configuration.interfaces[2].interfaceNumber
      );

      let { data } = await request.transferIn(endpoint.endpointNumber, 64);

      setReciverArea(new TextDecoder().decode(data));

      console.log(response);
    } catch (error) {
      setReciverArea("Something went wrong!");
      portRef.current.close();
      console.log(error, "error");
    }
  };

  const readFile = async (input) => {
    let file = input.target.files[0];
    let reader = new FileReader();
    reader.readAsArrayBuffer(file);
    reader.onload = function () {
      console.log(reader.result);
      send(reader);
    };
    reader.onerror = function () {
      console.log(reader.error);
    };
    console.log(input);
  };

  const send = (data) => {
    console.log("sending to serial:" + data.length);
    if (data.length === 0) return;
    console.log("sending to serial: [" + data + "]\n");

    //converting the data into to utf-8 format
    let view = new TextEncoder().encode(data);
    console.log(view);
    if (port) {
      //sending the data
      const { endpointNumber } =
        this.device_.configuration.interfaces[0].alternate.endpoints[1];
      return this.device_.transferOut(endpointNumber, data);
    }
  };
  //if devices change, print devices
  useEffect(() => {
    if (device > 0) console.log(device);
  }, [device]);

  return (
    <>
      <Head>
        <title>Delta WebUSB App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> {/* icon */}
      </Head>
      <h1>Delta WebUSB App demo</h1>
      <h2></h2>
      <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
        <button
          id="connect"
          onClick={connect}
          style={{ visibility: "visible", maxWidth: "max-content" }}
        >
          Connect To WebUSB Device
        </button>
        <div
          style={{
            marginTop: 100,
          }}
        >
          {/* <button id="update">Update</button> */}
          {/* <button id="read">Read FW</button> */}
          <input type="file" onChange={readFile}></input>
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            marginTop: 150,
          }}
        >
          <button id="submit">Send</button>
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            alignItems: "center",
            gap: 15,
          }}
        >
          <label htmlFor="editor">Sender: </label>
          <textarea
            id="editor"
            cols={30}
            onChange={(e) => setSenderArea(e.target.value)}
            value={senderArea}
          ></textarea>
          <label htmlFor="output"> Receiver: </label>
          <textarea
            id="output"
            cols={30}
            readOnly
            value={reciverArea}
          ></textarea>
        </div>
      </div>
    </>
  );
}
